# Config file for automatic testing at travis-ci.org

# Trying out new travis containers
# http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
sudo: false

language: python

# Leverage the pip cache
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.5
  - 3.4
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements/test.txt

# command to run tests, e.g. python setup.py test
script: python runtests.py

# Running codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
